"""
    apimaticcalculatorlib.apimatic_calculator_client

    This file was automatically generated by APIMATIC BETA v2.0 on 06/15/2016
"""
from apimaticcalculatorlib.http import *
from apimaticcalculatorlib.models import *
from apimaticcalculatorlib.controllers import *
from apimaticcalculatorlib.decorators import *
from apimaticcalculatorlib.api_exception import *

class APIMATICCalculatorClient(object):

    @lazy_property
    def simple_calculator_controller(self):
        return SimpleCalculatorController()



