# -*- coding: utf-8 -*-

"""
   apimaticcalculatorlib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/15/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "http://examples.apimatic.io/apps/calculator"


