# -*- coding: utf-8 -*-

"""
    apimaticcalculatorlibcontrollers.base_controller

    This file was automatically generated by APIMATIC BETA v2.0 on 06/15/2016
"""

from apimaticcalculatorlib.http.requests_client import *
from apimaticcalculatorlib.api_exception import APIException

class BaseController(object):

    """All controllers inherit from this base class. It manages shared HTTP clients and global API errors."""
    
    http_call_back = None
    http_client = RequestsClient()

    def __init__(self, client, call_back):
        if client != None:
            self.http_client = client
        if call_back != None:
            self.http_call_back = call_back

    def validate_response(self, response):
        if (response.status_code < 200) or (response.status_code > 206): #[200,206] = HTTP OK
            raise APIException("HTTP Response Not OK", response.status_code, response.raw_body)
